### ISSUE TITLE
NULL in strlcpy()

### ISSUE THREAD

**Issue by vorkauteer** [winlibs/net-snmp#6]
in [line](https://github.com/winlibs/net-snmp/blob/0c478089ece16d6346fbf464a9ef00d17f123fc3/agent/mibgroup/ucd-snmp/dlmod.c#L225) the tmp_path pointer appears with a NULL value and then no patterns in strlcpy.

**Comment by ndossche** [comment]
`tmp_path` is allocated and set here:
https://github.com/winlibs/net-snmp/blob/0c478089ece16d6346fbf464a9ef00d17f123fc3/agent/mibgroup/ucd-snmp/dlmod.c#L210-L214
The loop should execute at least once.
